<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Whojoo.PerformanceCounter\Whojoo.PerformanceCounter.csproj" />
    <ProjectReference Include="..\aspire.ServiceDefaults\aspire.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
